steps:
  - label: "check artifacts"
    command: |
      source ~/.cargo/env
      rustup default 1.59.0
      rustup target add wasm32-unknown-unknown
      ./scripts/build_all_docker.sh --check

  - label: "cargo test"
    command: |
      source ~/.cargo/env
      rustup default 1.59.0
      rustup target add wasm32-unknown-unknown
      ./scripts/test_all.sh
